apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-backend
  template:
    metadata:
      labels:
        app: capstone-backend
    spec:
      containers:
        - name: capstone-backend
          image: devops-capstone-backend:latest
