FROM node:18-alpine AS base

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

# taken from nextjs documentation. runs correct command based on preferred package manager
RUN \
    if [-f yarn.lock]; then yarn --frozen-lockfile; \
    elif [-f package-lock.json]; then npm ci; \
    elif [-f pnpm-lock.yaml]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
    else echo "Lockfile not found" && exit 1; \
    fi

COPY . .

RUN npm run build

# exposes port 3000
EXPOSE 3000

CMD ["npm", "start"]