FROM python:3.9

# set working directory
WORKDIR /usr/src/app

# copy dependecies to the working directory
COPY requirements.txt ./

# install the required dependencies specified in the requirements.txt file
RUN pip install --no-cache-dir -r requirements.txt

# copy local directory to working directory
COPY . .

# run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]